# [global]
command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=none

[title]
interval=1
#align=center
#separator=false
#min_width=1250

[layout]
label=
interval=1

[volume]
command=amixer -c 1 get Master | grep -E -o '[0-9][0-9][0-9]?%'
label=
interval=1

[time]
label=
command=date '+%d %b, %a %I:%M %p'
interval=30

