# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
    colors = true
    interval = 1
    output_format = i3bar
}


order += "volume master"
order += "ethernet enp2s0"
order += "wireless wlp3s0"
order += "battery 0"
order += "tztime utc"

wireless wlp3s0 {
	format_up   = "Yep %quality"
	format_down = "Nope"

    color_good     = "#90A458"
    color_degraded = "#AD995D"
    color_bad      = "#AD665D"
}

ethernet enp2s0 {
    format_up   = "Yep"
    format_down = "Nope"

    color_good     = "#90A458"
    color_degraded = "#AD995D"
    color_bad      = "#AD665D"
}

battery 0 {
	path			   = /sys/class/power_supply/BAT0/uevent
	last_full_capacity = true
    format			   = "%status %percentage %remaining"
    color_bad          = "#AD665D"
}

tztime utc {
    format = "%H:%M"
}

volume master {
	format		 = "Volume %volume"
	format_muted = "Volume X"
	device		 = "default"
	mixer		 = "Master"
	mixer_idx	 = 0
}
